# Generated by Django 5.2.6 on 2025-09-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('manager', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
