# Generated by Django 5.2.6 on 2025-09-06 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SynergySphere_app', '0001_initial'),
    ]

    operations = [
    ]
